// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxvygskbkbtdvhoqosci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4dnlnc2tia2J0ZHZob3Fvc2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDIwNDAsImV4cCI6MjA3NDU3ODA0MH0.yHl1o63FlfllAHGfEY1kdrTfzwxXXnzrvM-QWyetooY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});